### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by albatros2ko** [klange/assholedoth#3]
Do I need a specific compiler? It failed when I tried using VS 2013.

**Comment by klange** [comment]
... why are you trying to build this?

**Comment by albatros2ko** [comment]
Curiosity perhaps? Well, I guess this isn't supposed to be ran?

**Comment by klange** [comment]
You need to provide the output from Visual Studio so I can see how it's failing, but I suspect Visual Studio has dropped support for digraphs (an obscure and obtuse feature of older C and C++ standards that was deprecated in C++11).

**Comment by albatros2ko** [comment]
Yeah, Microsoft doesn't support digraphs anymore. Anyway, I managed to compile it with g++, it works.
